version: '3.8'

services:
  mineru-parser:
    build: .
    container_name: mineru-parser
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - MINERU_TOKEN=${MINERU_TOKEN}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3